# Generated by Django 5.2.6 on 2025-09-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='TIPO', max_length=50, null=True)),
                ('cantidad_de_tipo', models.FloatField(blank=True, db_column='CANTIDAD DE TIPO', null=True)),
                ('sucursal', models.CharField(blank=True, db_column='SUCURSAL', max_length=50, null=True)),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(blank=True, db_column='CANTIDAD', null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='TIPO', max_length=7, null=True)),
                ('cantidad', models.FloatField(blank=True, db_column='CANTIDAD', null=True)),
                ('fecha', models.DateTimeField(blank=True, db_column='FECHA', null=True)),
            ],
            options={
                'db_table': 'movimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('descripcion', models.TextField(blank=True, db_column='DESCRIPCION', null=True)),
                ('tipo', models.CharField(blank=True, db_column='TIPO', max_length=50, null=True)),
                ('precio_unitario', models.FloatField(blank=True, db_column='PRECIO_UNITARIO', null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='NOMBRE', max_length=100)),
                ('ubicacion', models.CharField(blank=True, db_column='UBICACION', max_length=150, null=True)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioCRUD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('sucursal', models.CharField(max_length=100)),
                ('cantidad', models.FloatField()),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
