# Generated by Django 5.2.6 on 2025-09-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviosEnCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('codigo_confirmacion', models.CharField(max_length=50)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.inventariocrud')),
            ],
        ),
    ]
