# Generated by Django 5.2.6 on 2025-09-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_enviosencurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviosencurso',
            name='paquete',
        ),
        migrations.AddField(
            model_name='enviosencurso',
            name='cantidad',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enviosencurso',
            name='producto',
            field=models.CharField(default='Sin producto', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enviosencurso',
            name='sucursal',
            field=models.CharField(default='Sin producto', max_length=100),
            preserve_default=False,
        ),
    ]
